redirectsOrigin = "inline"
headers = []

[functions]

[functions._ipx]
node_bundler = "nft"

[functions.___netlify-handler]
included_files = [".env", ".env.local", ".env.production", ".env.production.local", "./public/locales/**", "./next-i18next.config.js", ".next/server/**", ".next/serverless/**", ".next/*.json", ".next/BUILD_ID", ".next/static/chunks/webpack-middleware*.js", "!.next/server/**/*.js.nft.json", "!.next/server/**/*.map", "!**/node_modules/@next/swc*/**/*", "!node_modules/next/dist/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/compiled/webpack/bundle4.js", "!node_modules/next/dist/compiled/webpack/bundle5.js", "node_modules/styled-jsx/style.js", "!node_modules/sharp/**/*"]
external_node_modules = []
node_bundler = "nft"

[functions.___netlify-odb-handler]
included_files = [".env", ".env.local", ".env.production", ".env.production.local", "./public/locales/**", "./next-i18next.config.js", ".next/server/**", ".next/serverless/**", ".next/*.json", ".next/BUILD_ID", ".next/static/chunks/webpack-middleware*.js", "!.next/server/**/*.js.nft.json", "!.next/server/**/*.map", "!**/node_modules/@next/swc*/**/*", "!node_modules/next/dist/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/compiled/webpack/bundle4.js", "!node_modules/next/dist/compiled/webpack/bundle5.js", "node_modules/styled-jsx/style.js", "!node_modules/sharp/**/*"]
external_node_modules = []
node_bundler = "nft"

[functions."_api_*"]
included_files = [".env", ".env.local", ".env.production", ".env.production.local", "./public/locales/**", "./next-i18next.config.js", ".next/server/**", ".next/serverless/**", ".next/*.json", ".next/BUILD_ID", ".next/static/chunks/webpack-middleware*.js", "!.next/server/**/*.js.nft.json", "!.next/server/**/*.map", "!**/node_modules/@next/swc*/**/*", "!node_modules/next/dist/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm", "!node_modules/next/dist/compiled/webpack/bundle4.js", "!node_modules/next/dist/compiled/webpack/bundle5.js", "node_modules/styled-jsx/style.js", "!node_modules/sharp/**/*"]
external_node_modules = []
node_bundler = "nft"

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/home/mohnipaki/Downloads/dramabox-main/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NEXT_PRIVATE_TARGET = "server"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/favicon.ico"
to = "/favicon.ico"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]
Cookie = ["__prerender_bypass", "__next_preview_data"]

[redirects.headers]

[[redirects]]
from = "/placeholder-.svg"
to = "/placeholder-.svg"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]
Cookie = ["__prerender_bypass", "__next_preview_data"]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]
Cookie = ["__prerender_bypass", "__next_preview_data"]

[redirects.headers]

[[redirects]]
from = "/_next/data/fjUAki1EEwg7B812_H6fy/index.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/data/fjUAki1EEwg7B812_H6fy/sulih-suara.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sulih-suara"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/data/fjUAki1EEwg7B812_H6fy/terbaru.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terbaru"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/data/fjUAki1EEwg7B812_H6fy/terpopuler.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terpopuler"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/data/fjUAki1EEwg7B812_H6fy/detail/:bookId.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/detail/:bookId"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/data/fjUAki1EEwg7B812_H6fy/watch/:bookId.json"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/watch/:bookId"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]